<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="VerifyEmployeesStatusWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/VerifyEmployeesStatusWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/VerifyEmployeesStatusWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://Service.BusinessLogic.examsUnal.unal.co/">
    <import location="http://arch-skills/examsUnal/VerifyEmployeesStatus?wsdl" namespace="http://Service.BusinessLogic.examsUnal.unal.co/"/>
    <plnk:partnerLinkType name="VerifyEmployeesStatusLinkType">
        <plnk:role name="VerifyEmployeesStatusRole" portType="ns:VerifyEmployeesStatus"/>
    </plnk:partnerLinkType>
</definitions>
